// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJxaaJuL1Wk8RZMRqgfR2yNBO8LrmvoIQ',
    appId: '1:101067446262:web:495a5643bd9a7ac75599d7',
    messagingSenderId: '101067446262',
    projectId: 'auth-7a6b5',
    authDomain: 'auth-7a6b5.firebaseapp.com',
    storageBucket: 'auth-7a6b5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmgHCQHTeCYHern_KihY3ZktAtANWHGvU',
    appId: '1:101067446262:android:f3c08406238c1ed45599d7',
    messagingSenderId: '101067446262',
    projectId: 'auth-7a6b5',
    storageBucket: 'auth-7a6b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCED1pMd7u_IbxV_laPMoRPQe5fpX0fX7Q',
    appId: '1:101067446262:ios:7ff73abf81056ab55599d7',
    messagingSenderId: '101067446262',
    projectId: 'auth-7a6b5',
    storageBucket: 'auth-7a6b5.firebasestorage.app',
    iosBundleId: 'com.example.testingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJxaaJuL1Wk8RZMRqgfR2yNBO8LrmvoIQ',
    appId: '1:101067446262:web:94dcffd8e71121775599d7',
    messagingSenderId: '101067446262',
    projectId: 'auth-7a6b5',
    authDomain: 'auth-7a6b5.firebaseapp.com',
    storageBucket: 'auth-7a6b5.firebasestorage.app',
  );

}